-- Danske Bank-CSV'en har kun dato, ikke klokkeslæt. Flere posteringer samme
-- dag kan derfor ikke sorteres korrekt indbyrdes ud fra date alene - det gav
-- fejlagtig "nuværende saldo", fordi den forkerte postering blev regnet som
-- den seneste. import_seq stiger automatisk i den rækkefølge rækkerne
-- indsættes (som matcher CSV-filens rækkefølge, dvs. bankens egen
-- kronologiske rækkefølge), og bruges som sekundær sortering efter dato.
-- "by default" (ikke "always") så eksisterende rækker kan få deres
-- import_seq rettet præcist ud fra saldo-kæden ved denne migration, uden at
-- det forhindrer nye posteringer i bare at bruge sekvensens standardværdi.
alter table budget.transactions
  add column import_seq integer generated by default as identity;
